language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
  yarn: true
before_script:
  - "npm i -g gatsby"
script:
  - "npm run test"
deploy:
  provider: script
  script: "npm run deploy"
  on:
    branch: release
