language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
  yarn: true
script:
  - "yarn run test"
deploy:
  provider: script
  script: "yarn run deploy"
  on:
    branch: release
